#include "gpio.h"

void
GPIO_Init(void)
{
  /* UART5 GPIO CLK ENABLE */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOD_CLK_ENABLE();

  // CAN1 GPIO ENABLE
  __HAL_RCC_GPIOA_CLK_ENABLE();

  // CAN2 GPIO ENABLE
  __HAL_RCC_GPIOB_CLK_ENABLE();
}
